from __future__ import annotations

from typing import Dict, List


PROBE_REGISTRY: List[Dict[str, object]] = [
    {
        "probe_id": "identity.local_system_info",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["CimCmdlets"], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.identity.platform", "lens.identity.ids", "lens.health.uptime_seconds"],
        "timeout_s": 8,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.local_interfaces",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP", "NetAdapter"], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.connectivity.interfaces"],
        "timeout_s": 8,
        "max_items": 50,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.local_routes",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.connectivity.routes"],
        "timeout_s": 8,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.dns_resolve_external",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DnsClient"], "permissions": [], "admin": False},
        "inputs": {"targets": ["login.microsoftonline.com", "graph.microsoft.com"]},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 6,
        "max_items": 10,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.port_probe_external",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {"targets": ["graph.microsoft.com"], "ports": [443]},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 8,
        "max_items": 10,
        "risk": "safe",
    },
    {
        "probe_id": "config.firewall_profiles_local",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetSecurity"], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.config.firewall.profiles"],
        "timeout_s": 8,
        "max_items": 10,
        "risk": "safe",
    },
    {
        "probe_id": "health.time.local_status",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.health.time"],
        "timeout_s": 8,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "health.time.dc_offset",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.health.time"],
        "timeout_s": 12,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "health.time.ntp_offset",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"servers": ["pool.ntp.org"]},
        "outputs_to": ["lens.health.time"],
        "timeout_s": 12,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "config.certificates.machine_inventory",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"stores": ["My", "Root", "CA"], "expiring_days": 30},
        "outputs_to": ["lens.config.certificates"],
        "timeout_s": 12,
        "max_items": 500,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.tls_probe",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"targets": ["graph.microsoft.com", "login.microsoftonline.com"], "port": 443},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 12,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "health.process.inventory",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"include_command_line": False, "max_items": 200},
        "outputs_to": ["lens.health.processes"],
        "timeout_s": 20,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.service.process_map",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"max_items": 200},
        "outputs_to": ["lens.health.services"],
        "timeout_s": 20,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.resources.pressure",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.health.resources"],
        "timeout_s": 12,
        "max_items": 10,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.network_context",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP", "NetAdapter"], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.connectivity.context"],
        "timeout_s": 10,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.dns.multi_resolver",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DnsClient"], "permissions": [], "admin": False},
        "inputs": {"targets": ["graph.microsoft.com"], "resolvers": []},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 12,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.latency.external_endpoints",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {"targets": ["graph.microsoft.com", "login.microsoftonline.com"], "port": 443},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 12,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "dependencies.directory_local",
        "subject_kinds": ["admin_host"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {},
        "outputs_to": ["lens.dependencies.directory.current_dc"],
        "timeout_s": 6,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "identity.user_core",
        "subject_kinds": ["user"],
        "profile_min": "core",
        "tool": "graph",
        "requires": {"modules": [], "permissions": ["User.Read.All"], "admin": False},
        "inputs": {"user_id": "id_or_upn"},
        "outputs_to": ["lens.identity.principals.primary_user_upn", "lens.identity.ids"],
        "timeout_s": 8,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "authz.user_groups_core",
        "subject_kinds": ["user"],
        "profile_min": "core",
        "tool": "graph",
        "requires": {"modules": [], "permissions": ["Group.Read.All"], "admin": False},
        "inputs": {"user_id": "id_or_upn", "top": 200},
        "outputs_to": ["lens.authz.access.group_memberships"],
        "timeout_s": 10,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "authz.user_licenses_core",
        "subject_kinds": ["user"],
        "profile_min": "core",
        "tool": "graph",
        "requires": {"modules": [], "permissions": ["User.Read.All"], "admin": False},
        "inputs": {"user_id": "id_or_upn"},
        "outputs_to": ["lens.authz.access.licenses"],
        "timeout_s": 8,
        "max_items": 50,
        "risk": "safe",
    },
    {
        "probe_id": "authz.signin_summary_24h",
        "subject_kinds": ["user"],
        "profile_min": "core",
        "tool": "graph",
        "requires": {"modules": [], "permissions": ["AuditLog.Read.All"], "admin": False},
        "inputs": {"user_id": "id_or_upn", "lookback_hours": 24, "top": 50},
        "outputs_to": ["lens.authz.signins.summary", "lens.authz.signins.recent_failures"],
        "timeout_s": 12,
        "max_items": 50,
        "risk": "safe",
    },
    {
        "probe_id": "authz.ca_block_summary_24h",
        "subject_kinds": ["user"],
        "profile_min": "core",
        "tool": "graph",
        "requires": {"modules": [], "permissions": ["AuditLog.Read.All"], "admin": False},
        "inputs": {"user_id": "id_or_upn", "lookback_hours": 24, "top": 50},
        "outputs_to": ["lens.authz.policy.ca_blocks"],
        "timeout_s": 12,
        "max_items": 50,
        "risk": "safe",
    },
    {
        "probe_id": "identity.device_directory_record",
        "subject_kinds": ["device", "workstation", "server", "dc", "network_device"],
        "profile_min": "core",
        "tool": "graph",
        "requires": {"modules": [], "permissions": ["Device.Read.All"], "admin": False},
        "inputs": {"device_id_or_name": "device_id_or_hostname"},
        "outputs_to": ["lens.identity.join", "lens.identity.ids", "lens.identity.platform"],
        "timeout_s": 10,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.probe_dns_resolve_device",
        "subject_kinds": ["device", "workstation", "server", "dc", "network_device"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DnsClient"], "permissions": [], "admin": False},
        "inputs": {"target": "hostname_or_ip"},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 6,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.probe_ping_device",
        "subject_kinds": ["device", "workstation", "server", "dc", "network_device"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"target": "hostname_or_ip", "count": 4},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 6,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.probe_ports_device",
        "subject_kinds": ["device", "workstation", "server", "dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {"target": "hostname_or_ip", "ports": [443, 445], "optional_ports": [3389, 5986]},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 8,
        "max_items": 10,
        "risk": "safe",
    },
    {
        "probe_id": "identity.dc_record",
        "subject_kinds": ["dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["ActiveDirectory"], "permissions": [], "admin": True},
        "inputs": {"dc_name": "hostname"},
        "outputs_to": ["lens.identity.platform", "lens.identity.ids"],
        "timeout_s": 10,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "health.dcdiag_quick",
        "subject_kinds": ["dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": True},
        "inputs": {"dc_name": "hostname"},
        "outputs_to": ["lens.health.findings"],
        "timeout_s": 20,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.replication_summary",
        "subject_kinds": ["dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": True},
        "inputs": {},
        "outputs_to": ["lens.health.replication.summary"],
        "timeout_s": 20,
        "max_items": 100,
        "risk": "safe",
    },
    {
        "probe_id": "health.replication_partners",
        "subject_kinds": ["dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": True},
        "inputs": {"dc_name": "hostname"},
        "outputs_to": ["lens.health.replication.partners"],
        "timeout_s": 20,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.time_sync",
        "subject_kinds": ["dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": True},
        "inputs": {"dc_name": "hostname"},
        "outputs_to": ["lens.health.time"],
        "timeout_s": 8,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.port_probe_dc",
        "subject_kinds": ["dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {"target": "hostname_or_ip", "ports": [53, 88, 389, 445, 443]},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 8,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "identity.dns_server_record",
        "subject_kinds": ["dns_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DnsServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.identity.platform", "lens.identity.ids"],
        "timeout_s": 10,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "health.dns_service_status",
        "subject_kinds": ["dns_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DnsServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.health.services"],
        "timeout_s": 8,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "config.dns_zone_summary",
        "subject_kinds": ["dns_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DnsServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.config.dns.zones"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.port_probe_dns",
        "subject_kinds": ["dns_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {"target": "hostname_or_ip", "ports": [53]},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 6,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "identity.dhcp_server_record",
        "subject_kinds": ["dhcp_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DhcpServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.identity.platform", "lens.identity.ids"],
        "timeout_s": 10,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "health.dhcp_service_status",
        "subject_kinds": ["dhcp_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DhcpServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.health.services"],
        "timeout_s": 8,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "config.dhcp_scope_summary",
        "subject_kinds": ["dhcp_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DhcpServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.config.dhcp.scopes"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.dhcp_lease_summary",
        "subject_kinds": ["dhcp_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["DhcpServer"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.health.lease_summary"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "identity.file_server_record",
        "subject_kinds": ["file_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["SmbShare"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.identity.platform", "lens.identity.ids"],
        "timeout_s": 10,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "connectivity.port_probe_file_server",
        "subject_kinds": ["file_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["NetTCPIP"], "permissions": [], "admin": False},
        "inputs": {"target": "hostname_or_ip", "ports": [445]},
        "outputs_to": ["lens.connectivity.probes"],
        "timeout_s": 6,
        "max_items": 5,
        "risk": "safe",
    },
    {
        "probe_id": "health.smb_sessions_summary",
        "subject_kinds": ["file_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["SmbShare"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.health.smb.sessions"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.smb_openfiles_summary",
        "subject_kinds": ["file_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["SmbShare"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.health.smb.open_files"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "resource.share_reachability",
        "subject_kinds": ["file_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["SmbShare"], "permissions": [], "admin": False},
        "inputs": {"shares": []},
        "outputs_to": ["lens.config.shares"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "identity.print_server_record",
        "subject_kinds": ["print_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["PrintManagement"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.identity.platform", "lens.identity.ids"],
        "timeout_s": 10,
        "max_items": 1,
        "risk": "safe",
    },
    {
        "probe_id": "health.print_spooler_status",
        "subject_kinds": ["print_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["PrintManagement"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname"},
        "outputs_to": ["lens.health.services"],
        "timeout_s": 8,
        "max_items": 20,
        "risk": "safe",
    },
    {
        "probe_id": "resource.printers_summary",
        "subject_kinds": ["print_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["PrintManagement"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.config.printers"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "resource.print_queue_summary",
        "subject_kinds": ["print_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["PrintManagement"], "permissions": [], "admin": True},
        "inputs": {"server": "hostname", "max_items": 200},
        "outputs_to": ["lens.health.print_queues"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "resource.gpo_mapping_summary",
        "subject_kinds": ["print_server"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": ["GroupPolicy"], "permissions": [], "admin": True},
        "inputs": {"max_items": 200},
        "outputs_to": ["lens.dependencies.gpo_mappings"],
        "timeout_s": 12,
        "max_items": 200,
        "risk": "safe",
    },
    {
        "probe_id": "health.eventlog.summary",
        "subject_kinds": ["admin_host", "workstation", "server", "dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {
            "log_names": ["System", "Application"],
            "levels": ["Error", "Warning"],
            "time_window_hours": 24,
            "max_events": 500,
            "sample_size": 10,
        },
        "outputs_to": ["lens.health.eventlog_summary"],
        "timeout_s": 20,
        "max_items": 500,
        "risk": "safe",
    },
    {
        "probe_id": "config.registry.watchlist_snapshot",
        "subject_kinds": ["admin_host", "workstation", "server", "dc"],
        "profile_min": "core",
        "tool": "powershell",
        "requires": {"modules": [], "permissions": [], "admin": False},
        "inputs": {"watchlist_id": "network.core", "recurse_depth": 0, "max_items": 200},
        "outputs_to": ["lens.config.registry_watchlist"],
        "timeout_s": 20,
        "max_items": 200,
        "risk": "safe",
    },
]


def build_probe_registry() -> List[Dict[str, object]]:
    return list(PROBE_REGISTRY)
